# Generated by Django 5.2.6 on 2025-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('missao', models.TextField()),
                ('descricao', models.TextField()),
                ('respostaCorreta', models.CharField(max_length=150)),
                ('figura', models.ImageField(upload_to='')),
            ],
        ),
    ]
